### ISSUE TITLE
DeprecationWarnings when used with Webpack 4

### ISSUE THREAD

**Issue by jmullo** [Updater/peer-deps-externals-webpack-plugin#2]
(node:13928) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:13928) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead

**Comment by pmowrer** [comment]
Fixed by #3

**Comment by jmullo** [comment]
Perhaps also publish to NPM?

**Comment by pmowrer** [comment]
Ran into a snag with `npm` permissions, then forgot 😅 Now published!
